# Chap 05

## 5.1 pandas 자료구조 소개

### 5.1.1 Series

In [1]:
from pandas import Series, DataFrame

In [2]:
import pandas as pd

In [3]:
obj = Series([4,7,-5,3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [7]:
obj2 = Series([4,7,-5,3], index=['d','b','a','c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2['a']

-5

In [11]:
obj[['c','a','d']]

c   NaN
a   NaN
d   NaN
dtype: float64

In [13]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [15]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [16]:
import numpy as np
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
'b' in obj2

True

In [18]:
'e' in obj2

False

In [19]:
sdata = {'Ohio':30555,'Texas':71000,'Oregon':16000,'Utah':5000}

In [20]:
obj3=Series(sdata)

In [21]:
obj3

Ohio      30555
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [22]:
states=['California','Ohio','Oregon','Texas']

In [23]:
obj4=Series(sdata,index=states)

In [24]:
obj4

California      NaN
Ohio          30555
Oregon        16000
Texas         71000
dtype: float64

In [25]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
obj3

Ohio      30555
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [29]:
obj4

California      NaN
Ohio          30555
Oregon        16000
Texas         71000
dtype: float64

In [30]:
obj3 + obj4

California       NaN
Ohio           61110
Oregon         32000
Texas         142000
Utah             NaN
dtype: float64

In [31]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California      NaN
Ohio          30555
Oregon        16000
Texas         71000
Name: population, dtype: float64

In [32]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [33]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 5.1.2 DataFrame

In [34]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [35]:
frame = DataFrame(data)

In [37]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [38]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [39]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five'])

In [40]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [41]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [42]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [43]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [44]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [48]:
frame2.ix['three']   #index가 three

year     2002
state    Ohio
pop       3.6
debt     16.5
Name: three, dtype: object

In [49]:
frame2['debt'] = 16.5

In [50]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [51]:
frame2['debt']=np.arange(5.)

In [52]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [53]:
val=Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [54]:
frame2['dept'] = val

In [55]:
frame2

year   state  pop  debt  dept
one    2000    Ohio  1.5     0   NaN
two    2001    Ohio  1.7     1  -1.2
three  2002    Ohio  3.6     2   NaN
four   2001  Nevada  2.4     3  -1.5
five   2002  Nevada  2.9     4  -1.7

In [56]:
frame2['eastern'] = frame2.state == 'Ohio'

In [57]:
frame2

year   state  pop  debt  dept eastern
one    2000    Ohio  1.5     0   NaN    True
two    2001    Ohio  1.7     1  -1.2    True
three  2002    Ohio  3.6     2   NaN    True
four   2001  Nevada  2.4     3  -1.5   False
five   2002  Nevada  2.9     4  -1.7   False

In [58]:
del frame2['eastern']

In [59]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt', u'dept'], dtype='object')

In [60]:
frame2

year   state  pop  debt  dept
one    2000    Ohio  1.5     0   NaN
two    2001    Ohio  1.7     1  -1.2
three  2002    Ohio  3.6     2   NaN
four   2001  Nevada  2.4     3  -1.5
five   2002  Nevada  2.9     4  -1.7

In [61]:
pop = {'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [62]:
frame3 = DataFrame(pop)

In [63]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [64]:
frame3.T   #역치

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [65]:
DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [66]:
pdata={'Ohio':frame3['Ohio'][:-1],'Nevada':frame3['Nevada'][:2]}

In [67]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [68]:
pdata

{'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64, 'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64}

In [70]:
frame3.index.name='year';frame3.columns.name='state'

In [71]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [72]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [73]:
frame2.values

array([[2000L, 'Ohio', 1.5, 0.0, nan],
       [2001L, 'Ohio', 1.7, 1.0, -1.2],
       [2002L, 'Ohio', 3.6, 2.0, nan],
       [2001L, 'Nevada', 2.4, 3.0, -1.5],
       [2002L, 'Nevada', 2.9, 4.0, -1.7]], dtype=object)

### 5.1.3 색인 객체

In [74]:
obj = Series(range(3),index=['a','b','c'])

In [79]:
index = obj.index

In [80]:
index

Index([u'a', u'b', u'c'], dtype='object')

In [81]:
index[1:]

Index([u'b', u'c'], dtype='object')

In [83]:
index[1] = 'd'
#TypeError: Indexes does not support mutable operations

TypeError: Indexes does not support mutable operations

In [84]:
index = pd.Index(np.arange(3))

In [86]:
index

Int64Index([0, 1, 2], dtype='int64')

In [87]:
obj2 = Series([1.5, -2.5, 0], index=index)

In [88]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [89]:
obj2.index is index

True

In [90]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [91]:
'Ohio' in frame3

True

In [95]:
2000 in frame3  #column에 존재하는지

False

In [96]:
2000 in frame3.index  #index에 존재하는지

True

In [98]:
2003 in frame3.index

False

## 핵심기능

### 5.2.1 재색인

In [99]:
obj = Series([4.5, 7.2, -5.3, 3.6],index=['d','b','a','c'])

In [100]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [101]:
obj2 = obj.reindex(['a','b','c','d','e'])   #reindex 색인다시설정

In [102]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [104]:
obj.reindex(['a','b','c','d','e'],fill_value=0) #NaN을 0으로

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [105]:
obj3 = Series(['blue','purple','yellow'],index=[0,2,4])

In [106]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [108]:
obj3.reindex(range(6),method="ffill")
#range(6)까지 index를 앞의 값으로 채워준다

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [109]:
obj3 = Series(['blue','purple','yellow'],index=[0,2,4])

In [111]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [112]:
obj3.reindex(range(6),method="bfill")
# 뒤의 값으로 채워준다

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [113]:
frame = DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],
                  columns=['Ohio','Texas','California'])

In [114]:
frame = DataFrame(np.arange(9).reshape(3,3),index=['a','c','d'],
                  columns=['Ohio','Texas','California'])

In [116]:
frame.shape

(3, 3)

In [117]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [118]:
frame2 = frame.reindex(['a','b','c','d'])

In [119]:
frame2

Ohio  Texas  California
a     0      1           2
b   NaN    NaN         NaN
c     3      4           5
d     6      7           8

In [120]:
states = ['Texas', 'Utah', 'California']

In [121]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [122]:
frame.reindex(index=['a','b','c','d'],method='ffill',columns=states)

Texas  Utah  California
a      1   NaN           2
b      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [123]:
frame.ix[['a','b','c','d'],states]

Texas  Utah  California
a      1   NaN           2
b    NaN   NaN         NaN
c      4   NaN           5
d      7   NaN           8

### 5.2.2 하나의 로우 또는 칼럼 삭제하기

In [124]:
obj = Series(np.arange(5.),index=['a','b','c','d','e'])

In [125]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: float64

In [129]:
new_obj = obj.drop('c')  #c 를 drop한다

In [130]:
new_obj

a    0
b    1
d    3
e    4
dtype: float64

In [131]:
obj.drop(['d','c'])

a    0
b    1
e    4
dtype: float64

In [132]:
data = DataFrame(np.arange(16).reshape(4,4),index = ['Ohio','Colorado','Utah','New York'],
                 columns=['one','two','three','four'])

In [133]:
data.drop(['Colorado','Utah'])

one  two  three  four
Ohio        0    1      2     3
New York   12   13     14    15

In [134]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [135]:
data.drop(['two','four'],axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [136]:
data.drop(['Ohio','Utah'],axis=0)

one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

### 5.2.3 색인하기, 선택하기, 거르기

In [151]:
obj = Series(np.arange(4.),index=['a','b','c','d'])

In [152]:
obj

a    0
b    1
c    2
d    3
dtype: float64

In [153]:
obj['b']

1.0

In [154]:
obj[1]

1.0

In [155]:
obj[2:4]

c    2
d    3
dtype: float64

In [156]:
obj[['b', 'a', 'd']]

b    1
a    0
d    3
dtype: float64

In [157]:
obj[[1, 3]]

b    1
d    3
dtype: float64

In [158]:
obj[obj < 2]

a    0
b    1
dtype: float64

In [159]:
obj['b':'c']

b    1
c    2
dtype: float64

In [160]:
obj[1:3]

b    1
c    2
dtype: float64

In [161]:
obj['b':'c'] = 5
obj

a    0
b    5
c    5
d    3
dtype: float64

In [163]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])

In [164]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [165]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [166]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [167]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [168]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [169]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [170]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [171]:
data[data < 5] = 0

In [172]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [173]:
data.ix['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [174]:
data.ix[['Colorado', 'Utah'], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [175]:
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [176]:
data.ix[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [177]:
data.ix[data.three > 5, :3]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14